[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#044A30"
backgroundColor = "#E8E8E8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A2E28"
font = "sans serif"

[client]
toolbarMode = "viewer"
